version: '3'

services:
  icecast-analytics:

    # Uncomment to build local copy rather than pulling from docker hub.
    # build: .

    image: bushrangers/docker-icecast-google-analytics

    container_name: icecast-analytics
    restart: always
    privileged:  true
    network_mode: host

    volumes:
        - ./config/config.xml:/config/config.xml